Fix NPE in Power Menu when pressing volume buttons
Due to contexts being null the pressing of either volume button
within the Power Menu causes a fatal exception.

Example logcat message:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object
  android.content.Context.getSystemService(java.lang.String)' on a null object reference
at android.media.session.MediaSessionLegacyHelper.<init>(MediaSessionLegacyHelper.java:67)

Change-Id: I7719fc8823fef93556f5a9ab088a77b73cf7eeff